import { Device } from "scripting"

export const isGerman = Device.systemLanguageCode.toLowerCase().startsWith("de")

export const EN = {
  title: "Gen1Recomp Suite",
  close: "Close",
  eyebrow: "GENUINE ENGINE · LOCAL-FIRST",
  heroTitle: "Real Gen1Recomp. On device.",
  heroBody: "Run the hand-written Lua/LÖVE recreation locally with ROM data you provide. No emulator and no ROM uploads.",
  importGames: "Import games",
  library: "Library",
  games: "games",
  game: "game",
  noGames: "Bring your own cartridge dump",
  noGamesBody: "Import canonical Pokémon Red, Blue, Yellow, or Gold ROM revisions. Files are validated and copied into private local storage.",
  chooseFiles: "Choose ROM files",
  actions: "Tools",
  official: "Official iOS release",
  officialBody: "Check or download on demand",
  about: "Runtime & privacy",
  aboutBody: "Architecture, saves and licences",
  engine: "Bundled engine",
  engineBody: "Gen1Recomp v0.1.78 · LÖVE 11.5 WASM",
  recompReady: "Supported by Gen1Recomp",
  earlySupport: "Gold beta support",
  unsupported: "Unsupported legacy import",
  importing: "Validating ROMs locally…",
  checking: "Checking GitHub…",
  downloading: "Downloading & verifying IPA…",
  importedTitle: "Import complete",
  importFailed: "Nothing imported",
  cancel: "Cancel",
  play: "Play in Gen1Recomp",
  details: "Game details",
  cover: "Change cover",
  export: "Export ROM & synced saves",
  delete: "Remove from library",
  resetCover: "Restore suite cover",
  chooseCover: "Choose an image",
  deleteTitle: "Remove this game?",
  deleteBody: "The locally copied ROM and custom cover will be removed. Choose separately whether this game’s synchronized Gen1Recomp saves should also be erased.",
  keepSaves: "Remove ROM · keep saves",
  eraseSaves: "Remove ROM & saves",
  deleteConfirmTitle: "Confirm removal",
  deleteConfirmKeep: "The ROM will be removed. Synchronized Gen1Recomp saves will be kept for a later re-import.",
  deleteConfirmErase: "The ROM and this game version’s synchronized saves will be permanently erased. Shared player settings remain.",
  remove: "Remove",
  runtimeNoticeTitle: "Genuine Gen1Recomp web port",
  runtimeNotice: "This launches the active Gen1Recomp engine’s Lua game code in a local LÖVE 11.5 WebAssembly runtime—not a Game Boy emulator. The first launch extracts ROM-derived assets locally and may take 20–30 seconds. Enabled native mods are injected from your local mod library. On-screen controls appear automatically.",
  continue: "Continue",
  continueDontShow: "Continue & don’t show again",
  releaseTitle: "Official Gen1Recomp",
  downloadIPA: "Download verified iOS IPA",
  releaseNotes: "Open release notes",
  downloadTitle: "Download the official IPA?",
  downloadBody: "The IPA stays in your Scripting Documents folder and is checked against GitHub’s SHA-256 digest. Scripting cannot install it; iOS will show the share/open menu afterward.",
  download: "Download",
  downloadReady: "Verified download ready",
  privacyTitle: "How this build works",
  privacyBody: "The bundled runtime is the actual Gen1Recomp Lua/LÖVE recreation. At launch, temporary local scripts inject LÖVE WebAssembly, that code, the selected user ROM, and installed mod files into a file-only WebView. They are deleted when the player closes. No listening server, Scripting PRO API, or runtime network request is used.",
  saveBody: "ROM-derived caches remain in WebKit’s local IndexedDB when available. Saves and the active mod profile are synchronized to the suite’s local Documents folder and restored on the next launch. Every launch uses the same private local runtime path.",
  licenceBody: "Gen1Recomp v0.1.78 and Davidobot/love.js at c4f04e1 are MIT-licensed. The browser compatibility patches and pure-Lua bit module are included and documented. No copyrighted ROM data is bundled.",
  error: "Something went wrong",
  coverUpdated: "Cover updated",
  coverReset: "Suite cover restored",
  exported: "Export completed",
  statusLocal: "Local & private",
  networkHint: "Normal play is offline. Network access occurs only when you explicitly check/download an app or mod release, or open release notes/source pages.",
  emptyStatus: "ROMs never leave this device.",
  goldCaveat: "Gold support in Gen1Recomp v0.1.78 is beta and incomplete.",
  unsupportedCaveat: "This item was imported by an older suite version. The emulator has been removed, so it cannot be launched here; you can still export or delete it.",
  firstLaunch: "First launch builds a local ROM-derived cache. Later launches reuse it.",
  mods: "Mods",
  modsBody: "Install native Gen1Recomp mod ZIPs, choose what loads, and check trusted GitHub releases on demand.",
  installedMods: "installed",
  activeMods: "active",
  modHealth: "Mod health",
  modHealthReady: "Mod setup looks ready",
  modHealthReadyBody: "No missing enabled dependencies or active declared conflicts were found.",
  modHealthIssues: "mod setup issue(s)",
  missingDependency: "Missing dependency",
  disabledDependency: "Disabled dependency",
  activeConflict: "Active conflict",
  loadReportTitle: "About LOAD REPORT",
  loadReportBody: "Gen1Recomp compares the enabled mod set stored in a save with the set active now. After installing, disabling, removing, or updating mods, “no longer active” and “newly active” is an informational safety report—not an import failure. Continue only when the listed change is intentional; content-heavy mods can still require their own migration instructions.",
  largeModLibrary: "Large library: validated mods are kept as packed archives and mounted lazily. A first launch may still optimize ROM-derived artwork in the background.",
  modStorage: "Local mod payload",
  modScanning: "Scanning paths",
  modVerifying: "Verifying files",
  modPacking: "Preparing fast launch package",
  modPacked: "Packed fast launch",
  modLegacy: "Legacy expanded storage",
  installFromGitHub: "Install from GitHub",
  installFromGitHubBody: "Paste a repository or exact release URL. Nothing is downloaded until you confirm the digest-published ZIP.",
  exportDiagnostics: "Export console diagnostics",
  diagnosticsBody: "Exports the complete persistent runtime console trace plus component, setting, performance, and mod context. Logs are local until you explicitly share them. They exclude ROM bytes, save contents, original ROM filenames, hashes, and cover data, but engine or mod messages can contain technical paths or gameplay state.",
  diagnosticsReady: "Console diagnostics prepared",
  consoleDiagnostics: "Console diagnostics",
  consoleDiagnosticsBody: "Always-on local capture of browser console output, JavaScript errors and rejections, Emscripten abort/exit details, LÖVE output, WebGL events, package loading, native bridge stages, save synchronization, and cleanup. Messages are not sampled or shortened; oversized messages are preserved in numbered parts.",
  diagnosticsFormat: "Export format",
  diagnosticsFormatBody: "TXT is easiest to read and send for debugging. JSON preserves structured context, JSONL preserves the raw event stream, and CSV opens in spreadsheet tools.",
  diagnosticsTXT: "Readable complete log (.txt)",
  diagnosticsJSON: "Structured report (.json)",
  diagnosticsJSONL: "Raw event stream (.jsonl)",
  diagnosticsCSV: "Spreadsheet table (.csv)",
  diagnosticsEntries: "events",
  diagnosticsSessions: "sessions",
  diagnosticsErrors: "error events",
  diagnosticsNoError: "No captured error yet.",
  diagnosticsLastError: "Latest captured error",
  clearDiagnostics: "Clear console logs",
  clearDiagnosticsBody: "Delete the active and previous local console traces? This cannot be undone. Export them first if they are needed for debugging.",
  diagnosticsCleared: "Console logs cleared",
  clear: "Clear",
  fatalDiagnosticsHint: "The full error and stack were saved. Reopen the suite and export Settings → Console diagnostics.",
  noMods: "No mods installed. Vanilla Gen1Recomp remains unchanged.",
  importMod: "Import mod ZIP",
  dramaticShape: "Dramatic Shape Voxel Mod",
  dramaticBody: "External voxel/3D mod · after enabling, tap SELECT in free roam to cycle views",
  modSecurityTitle: "Install native mod code?",
  modSecurityBody: "Gen1Recomp mods are executable Lua code and can patch engine internals. Install only ZIPs from authors you trust. The suite checks paths, size, manifest structure, and forbidden ROM/save payloads, but cannot prove arbitrary code is harmless.",
  modImporting: "Validating mod ZIP locally…",
  modInstalled: "Mod installed",
  modUpdated: "Mod updated",
  modCheck: "Check for update",
  modChecking: "Checking mod release…",
  modDownloading: "Downloading & verifying mod…",
  enableMod: "Enable",
  disableMod: "Disable",
  removeMod: "Remove mod",
  removeModBody: "The installed mod files will be deleted. Game saves and shared options remain.",
  modDetails: "Mod details",
  modSettings: "Mod settings",
  modSettingsCount: "settings",
  restoreModDefaults: "Restore genuine defaults",
  restoreModDefaultsBody: "Remove this mod’s native overrides and restore every captured setting to the default declared by the installed mod version? Visual performance presets will stay suppressed for this mod until you choose a performance profile again.",
  modDefaultsRestored: "Genuine mod defaults restored",
  modSettingsDiscovery: "Settings discovery required",
  modSettingsDiscoveryBody: "Launch a supported game once with this mod enabled. Genuine Gen1Recomp will capture the bounded option declarations the mod exposes, then they will appear here. The native dashboard never executes installed Lua to discover settings.",
  noModSettings: "This installed mod exposed no supported toggle, choice, number, or text settings during its latest genuine Gen1Recomp load.",
  modSettingsDeclarative: "Read from a strictly literal, data-only options_schema; no Lua was executed by the dashboard.",
  modSettingsRuntime: "Captured as bounded primitive data after the mod loaded inside genuine Gen1Recomp; the dashboard did not execute it.",
  modSettingsApply: "Native changes apply on the next game launch. In-game changes are mirrored back after save synchronization.",
  invalidModNumber: "Enter a finite number inside the range declared by the mod.",
  back: "Back",
  openSource: "Open source page",
  noUpdate: "This mod is already current.",
  noUpdateSource: "This mod does not declare a valid GitHub update source.",
  modRestart: "Changes apply on the next game launch. Installed mods also appear under START → MODS inside Gen1Recomp.",
  modPermissions: "Declared permissions",
  modNone: "None",
  install: "Install",
  update: "Update",
  replace: "Replace",
  dashboard: "Home",
  gamesTab: "Games",
  modsTab: "Mods",
  settingsTab: "Settings",
  continuePlaying: "Continue playing",
  dashboardSummary: "Your local games, runtime health, and recent performance at a glance.",
  performance: "Performance",
  performanceProfile: "Visual mod profile",
  profileBalanced: "Balanced",
  profileBalancedBody: "Recommended for phones: disables cast shadows and costly full reflections, keeps atmosphere and sky reflections.",
  profileEfficient: "Efficient",
  profileEfficientBody: "Maximum smoothness and battery life: disables shadows, atmosphere, antialiasing, and water reflections.",
  profileQuality: "Mod defaults",
  profileQualityBody: "Clears suite-managed visual options so the mod’s genuine defaults return. Best quality, but Dramatic Shape may stutter on phones.",
  measuredPerformance: "Last measured session",
  noMeasurement: "Play for at least ten seconds to collect local frame metrics.",
  saveSync: "Save mirror interval",
  automaticChecks: "Automatic update checks",
  automaticChecksBody: "Opt-in checks only; nothing is installed automatically.",
  updateFrequency: "Check frequency",
  updateCenter: "Update Center",
  updateCenterBody: "Gen1Recomp, LÖVE Web runtime, and every updateable mod in one place.",
  downloadManager: "Download Manager",
  downloadManagerBody: "Automatic retries, safe HTTP resume, and integrity verification.",
  noDownloads: "No downloads",
  noDownloadsBody: "Component, IPA, and GitHub mod downloads appear here.",
  downloadPartialNotice: "Partial data remains local after interruption. If a server ignores Range, the file restarts cleanly; partial data is never installed.",
  downloadQueued: "Queued",
  downloadInProgress: "Downloading",
  downloadRetry: "Retry",
  downloadVerifying: "Verifying integrity",
  downloadPaused: "Paused · resumable",
  downloadCompleted: "Verified · ready",
  downloadFailed: "Failed · resumable",
  pause: "Pause",
  resume: "Resume",
  clearDownload: "Clear",
  httpResume: "HTTP resume",
  cleanRestart: "clean restart",
  cancelDownloadTitle: "Cancel download?",
  cancelDownloadBody: "Saved partial data will be removed safely.",
  cancelDownloadAction: "Cancel download",
  resumingDownload: "resuming",
  resumedDownloadReady: "verified; reopen its action to install",
  checkEverything: "Check all components",
  updateAllMods: "Update all available mods",
  engineComponent: "Gen1Recomp engine",
  runtimeComponent: "LÖVE Web runtime",
  bundled: "Bundled",
  installedComponent: "Installed override",
  current: "Current",
  updateAvailableLabel: "Update available",
  sourceChanged: "New upstream source exists; install only a compatible runtime bundle.",
  installEngineUpdate: "Install engine update",
  executionLayerComponent: "Execution layer",
  importExecutionLayer: "Import execution-layer update",
  resetExecutionLayer: "Restore generated execution layer",
  executionLayerNotice: "Execution layers contain executable Lua and run before the immutable core. Import only a layer you trust. The suite requires a newer layer version, exact core compatibility, revision 9, deterministic file hashes, and transactional activation.",
  importRuntimeBundle: "Import runtime bundle",
  resetEngine: "Restore bundled engine",
  resetRuntime: "Restore bundled Web runtime",
  runtimeBundleNotice: "Runtime bundles contain executable JavaScript and WebAssembly. Import only a compatibility/no-pthreads bundle you trust; all declared hashes and WebAssembly headers are verified.",
  checkingEverything: "Checking engine, runtime, and mods…",
  checkedEverything: "Update check complete",
  noUpdates: "Everything updateable is current.",
  updatesFound: "updates available",
  openRuntimeSource: "Open runtime source",
  profileAppliedNextLaunch: "The profile applies on the next launch and is reflected in the mod’s own options.",
  externalModNotice: "This is an external community project and is not bundled or redistributed by the suite. Its repository describes itself as a faithful copy of Dramatic Shape 1.8.2 and restricts redistribution of later code. The ZIP is fetched directly from its GitHub release only after confirmation.",
}

export const DE: typeof EN = {
  title: "Gen1Recomp Suite",
  close: "Schließen",
  eyebrow: "ECHTE ENGINE · LOKAL",
  heroTitle: "Echtes Gen1Recomp. Auf dem Gerät.",
  heroBody: "Die handgeschriebene Lua/LÖVE-Neuimplementierung läuft lokal mit deinen ROM-Daten. Kein Emulator und keine ROM-Uploads.",
  importGames: "Spiele importieren",
  library: "Bibliothek",
  games: "Spiele",
  game: "Spiel",
  noGames: "Eigenen Cartridge-Dump hinzufügen",
  noGamesBody: "Importiere kanonische ROM-Versionen von Pokémon Rot, Blau, Gelb oder Gold. Dateien werden geprüft und privat lokal kopiert.",
  chooseFiles: "ROM-Dateien auswählen",
  actions: "Werkzeuge",
  official: "Offizielles iOS-Release",
  officialBody: "Nur bei Bedarf prüfen oder laden",
  about: "Runtime & Datenschutz",
  aboutBody: "Architektur, Spielstände und Lizenzen",
  engine: "Gebündelte Engine",
  engineBody: "Gen1Recomp v0.1.78 · LÖVE 11.5 WASM",
  recompReady: "Von Gen1Recomp unterstützt",
  earlySupport: "Gold-Beta-Support",
  unsupported: "Nicht unterstützter Altimport",
  importing: "ROMs werden lokal geprüft…",
  checking: "GitHub wird geprüft…",
  downloading: "IPA wird geladen & verifiziert…",
  importedTitle: "Import abgeschlossen",
  importFailed: "Nichts importiert",
  cancel: "Abbrechen",
  play: "In Gen1Recomp spielen",
  details: "Spieldetails",
  cover: "Cover ändern",
  export: "ROM & synchronisierte Spielstände exportieren",
  delete: "Aus Bibliothek entfernen",
  resetCover: "Suite-Cover wiederherstellen",
  chooseCover: "Bild auswählen",
  deleteTitle: "Dieses Spiel entfernen?",
  deleteBody: "Die lokal kopierte ROM und das eigene Cover werden entfernt. Wähle separat, ob auch die synchronisierten Gen1Recomp-Spielstände dieser Version gelöscht werden sollen.",
  keepSaves: "ROM entfernen · Spielstände behalten",
  eraseSaves: "ROM & Spielstände entfernen",
  deleteConfirmTitle: "Entfernen bestätigen",
  deleteConfirmKeep: "Die ROM wird entfernt. Synchronisierte Gen1Recomp-Spielstände bleiben für einen späteren Reimport erhalten.",
  deleteConfirmErase: "ROM und synchronisierte Spielstände dieser Spielversion werden endgültig gelöscht. Gemeinsame Player-Einstellungen bleiben erhalten.",
  remove: "Entfernen",
  runtimeNoticeTitle: "Echter Gen1Recomp-Web-Port",
  runtimeNotice: "Hier läuft der Lua-Spielcode der aktiven Gen1Recomp-Engine in einer lokalen LÖVE-11.5-WebAssembly-Runtime – kein Game-Boy-Emulator. Beim ersten Start werden ROM-abgeleitete Assets lokal extrahiert; das kann 20–30 Sekunden dauern. Aktivierte native Mods werden aus deiner lokalen Mod-Bibliothek injiziert. Bildschirmtasten erscheinen automatisch.",
  continue: "Weiter",
  continueDontShow: "Weiter & nicht erneut zeigen",
  releaseTitle: "Offizielles Gen1Recomp",
  downloadIPA: "Verifiziertes iOS-IPA laden",
  releaseNotes: "Release-Notizen öffnen",
  downloadTitle: "Offizielles IPA laden?",
  downloadBody: "Das IPA bleibt im Scripting-Dokumenteordner und wird mit GitHubs SHA-256-Digest geprüft. Scripting kann es nicht installieren; anschließend erscheint das iOS-Menü zum Teilen/Öffnen.",
  download: "Laden",
  downloadReady: "Verifizierter Download bereit",
  privacyTitle: "So funktioniert dieser Build",
  privacyBody: "Die gebündelte Runtime ist die echte Gen1Recomp-Lua/LÖVE-Neuimplementierung. Beim Start injizieren temporäre lokale Skripte LÖVE-WebAssembly, diesen Code, die gewählte Nutzer-ROM und installierte Mod-Dateien in eine reine Datei-WebView. Beim Schließen werden sie gelöscht. Es gibt keinen lauschenden Server, keine Scripting-PRO-API und keine Runtime-Netzwerkanfrage.",
  saveBody: "ROM-abgeleitete Caches bleiben, sofern verfügbar, lokal in WebKits IndexedDB. Spielstände und das aktive Mod-Profil werden in den lokalen Dokumenteordner der Suite synchronisiert und beim nächsten Start wiederhergestellt. Jeder Start nutzt denselben privaten lokalen Runtime-Pfad.",
  licenceBody: "Gen1Recomp v0.1.78 und Davidobot/love.js bei c4f04e1 stehen unter MIT. Browser-Kompatibilitätspatches und das Pure-Lua-Bitmodul sind enthalten und dokumentiert. Urheberrechtlich geschützte ROM-Daten werden nicht mitgeliefert.",
  error: "Etwas ist schiefgelaufen",
  coverUpdated: "Cover aktualisiert",
  coverReset: "Suite-Cover wiederhergestellt",
  exported: "Export abgeschlossen",
  statusLocal: "Lokal & privat",
  networkHint: "Normales Spielen ist offline. Netzwerkzugriff erfolgt nur beim bewussten Prüfen/Laden eines App- oder Mod-Releases sowie beim Öffnen von Release-/Quellseiten.",
  emptyStatus: "ROMs verlassen dieses Gerät nie.",
  goldCaveat: "Gold-Support in Gen1Recomp v0.1.78 ist Beta und unvollständig.",
  unsupportedCaveat: "Dieser Eintrag stammt aus einer älteren Suite-Version. Der Emulator wurde entfernt; der Eintrag kann daher nicht gestartet, aber weiterhin exportiert oder gelöscht werden.",
  firstLaunch: "Der erste Start baut einen lokalen ROM-abgeleiteten Cache. Spätere Starts verwenden ihn erneut.",
  mods: "Mods",
  modsBody: "Native Gen1Recomp-Mod-ZIPs installieren, Starts gezielt steuern und vertrauenswürdige GitHub-Releases nur bei Bedarf prüfen.",
  installedMods: "installiert",
  activeMods: "aktiv",
  modHealth: "Mod-Zustand",
  modHealthReady: "Mod-Konfiguration sieht bereit aus",
  modHealthReadyBody: "Keine fehlenden aktivierten Abhängigkeiten oder aktiven deklarierten Konflikte gefunden.",
  modHealthIssues: "Problem(e) in der Mod-Konfiguration",
  missingDependency: "Fehlende Abhängigkeit",
  disabledDependency: "Deaktivierte Abhängigkeit",
  activeConflict: "Aktiver Konflikt",
  loadReportTitle: "Zum LOAD REPORT",
  loadReportBody: "Gen1Recomp vergleicht die im Spielstand gespeicherte aktive Mod-Menge mit der jetzt aktiven Menge. Nach Installation, Deaktivierung, Entfernung oder Update sind „no longer active“ und „newly active“ ein informativer Sicherheitsbericht – kein Importfehler. Fahre nur fort, wenn die aufgelistete Änderung beabsichtigt ist; umfangreiche Mods können zusätzlich eigene Migrationshinweise haben.",
  largeModLibrary: "Große Bibliothek: Geprüfte Mods bleiben als gepackte Archive erhalten und werden verzögert eingebunden. ROM-abgeleitete Grafiken können beim ersten Start im Hintergrund optimiert werden.",
  modStorage: "Lokale Mod-Nutzdaten",
  modScanning: "Pfade werden geprüft",
  modVerifying: "Dateien werden verifiziert",
  modPacking: "Schnellstart-Paket wird vorbereitet",
  modPacked: "Gepackter Schnellstart",
  modLegacy: "Ältere entpackte Ablage",
  installFromGitHub: "Von GitHub installieren",
  installFromGitHubBody: "Füge eine Repository- oder genaue Release-URL ein. Erst nach Bestätigung wird das ZIP mit veröffentlichtem Hash geladen.",
  exportDiagnostics: "Console-Diagnose exportieren",
  diagnosticsBody: "Exportiert den vollständigen persistenten Runtime-Console-Trace samt Komponenten-, Einstellungs-, Performance- und Mod-Kontext. Die Logs bleiben lokal, bis du sie ausdrücklich teilst. ROM-Daten, Save-Inhalte, ursprüngliche ROM-Dateinamen, Hashes und Cover-Daten sind ausgeschlossen; Engine- oder Mod-Meldungen können jedoch technische Pfade oder Spielzustände enthalten.",
  diagnosticsReady: "Console-Diagnose vorbereitet",
  consoleDiagnostics: "Console-Diagnose",
  consoleDiagnosticsBody: "Ständige lokale Erfassung von Browser-Console, JavaScript-Fehlern und Promise-Ablehnungen, Emscripten-Abbruch/Exit, LÖVE-Ausgaben, WebGL-Ereignissen, Paketladen, nativen Bridge-Schritten, Save-Synchronisierung und Cleanup. Meldungen werden weder gesampelt noch gekürzt; große Meldungen bleiben in nummerierten Teilen vollständig erhalten.",
  diagnosticsFormat: "Exportformat",
  diagnosticsFormatBody: "TXT ist am einfachsten zu lesen und für die Fehlersuche weiterzugeben. JSON bewahrt den strukturierten Kontext, JSONL den rohen Event-Stream und CSV lässt sich in Tabellenprogrammen öffnen.",
  diagnosticsTXT: "Vollständiges lesbares Log (.txt)",
  diagnosticsJSON: "Strukturierter Bericht (.json)",
  diagnosticsJSONL: "Roher Event-Stream (.jsonl)",
  diagnosticsCSV: "Tabellenformat (.csv)",
  diagnosticsEntries: "Ereignisse",
  diagnosticsSessions: "Sitzungen",
  diagnosticsErrors: "Fehlerereignisse",
  diagnosticsNoError: "Noch kein Fehler erfasst.",
  diagnosticsLastError: "Zuletzt erfasster Fehler",
  clearDiagnostics: "Console-Logs löschen",
  clearDiagnosticsBody: "Aktiven und vorherigen lokalen Console-Trace löschen? Das kann nicht rückgängig gemacht werden. Exportiere die Logs zuerst, falls sie für die Fehlersuche benötigt werden.",
  diagnosticsCleared: "Console-Logs gelöscht",
  clear: "Löschen",
  fatalDiagnosticsHint: "Der vollständige Fehler samt Stack wurde gespeichert. Öffne die Suite erneut und exportiere Einstellungen → Console-Diagnose.",
  noMods: "Keine Mods installiert. Gen1Recomp bleibt unverändert.",
  importMod: "Mod-ZIP importieren",
  dramaticShape: "Dramatic Shape Voxel Mod",
  dramaticBody: "Externe Voxel-/3D-Mod · aktivieren, dann in freier Bewegung SELECT tippen",
  modSecurityTitle: "Nativen Mod-Code installieren?",
  modSecurityBody: "Gen1Recomp-Mods sind ausführbarer Lua-Code und können interne Engine-Funktionen verändern. Installiere nur ZIPs vertrauenswürdiger Autoren. Die Suite prüft Pfade, Größen, Manifest-Struktur sowie verbotene ROM-/Save-Payloads, kann aber beliebigen Code nicht als harmlos beweisen.",
  modImporting: "Mod-ZIP wird lokal geprüft…",
  modInstalled: "Mod installiert",
  modUpdated: "Mod aktualisiert",
  modCheck: "Auf Update prüfen",
  modChecking: "Mod-Release wird geprüft…",
  modDownloading: "Mod wird geladen & verifiziert…",
  enableMod: "Aktivieren",
  disableMod: "Deaktivieren",
  removeMod: "Mod entfernen",
  removeModBody: "Die installierten Mod-Dateien werden gelöscht. Spielstände und gemeinsame Einstellungen bleiben erhalten.",
  modDetails: "Mod-Details",
  modSettings: "Mod-Einstellungen",
  modSettingsCount: "Einstellungen",
  restoreModDefaults: "Echte Standards wiederherstellen",
  restoreModDefaultsBody: "Alle nativen Überschreibungen dieser Mod entfernen und jede erfasste Einstellung auf den von der installierten Mod-Version deklarierten Standard setzen? Visuelle Performance-Vorgaben bleiben für diese Mod unterdrückt, bis erneut ein Performance-Profil gewählt wird.",
  modDefaultsRestored: "Echte Mod-Standards wiederhergestellt",
  modSettingsDiscovery: "Einstellungen müssen erfasst werden",
  modSettingsDiscoveryBody: "Starte einmal ein unterstütztes Spiel mit aktivierter Mod. Das echte Gen1Recomp erfasst die begrenzten Optionsdeklarationen der Mod; danach erscheinen sie hier. Das native Dashboard führt zur Erkennung niemals installierten Lua-Code aus.",
  noModSettings: "Diese installierte Mod hat beim letzten echten Gen1Recomp-Start keine unterstützten Schalter-, Auswahl-, Zahlen- oder Texteinstellungen bereitgestellt.",
  modSettingsDeclarative: "Aus einem streng literalen, reinen Daten-options_schema gelesen; das Dashboard hat keinen Lua-Code ausgeführt.",
  modSettingsRuntime: "Als begrenzte primitive Daten erfasst, nachdem die Mod im echten Gen1Recomp geladen wurde; das Dashboard hat sie nicht ausgeführt.",
  modSettingsApply: "Native Änderungen gelten beim nächsten Spielstart. Änderungen im Spiel werden nach der Save-Synchronisierung zurückgespiegelt.",
  invalidModNumber: "Gib eine endliche Zahl im von der Mod deklarierten Bereich ein.",
  back: "Zurück",
  openSource: "Quellseite öffnen",
  noUpdate: "Diese Mod ist bereits aktuell.",
  noUpdateSource: "Diese Mod enthält keine gültige GitHub-Updatequelle.",
  modRestart: "Änderungen gelten beim nächsten Spielstart. Installierte Mods erscheinen außerdem in Gen1Recomp unter START → MODS.",
  modPermissions: "Deklarierte Berechtigungen",
  modNone: "Keine",
  install: "Installieren",
  update: "Aktualisieren",
  replace: "Ersetzen",
  dashboard: "Start",
  gamesTab: "Spiele",
  modsTab: "Mods",
  settingsTab: "Einstellungen",
  continuePlaying: "Weiterspielen",
  dashboardSummary: "Lokale Spiele, Runtime-Status und letzte Performance auf einen Blick.",
  performance: "Performance",
  performanceProfile: "Profil für visuelle Mods",
  profileBalanced: "Ausgewogen",
  profileBalancedBody: "Für Smartphones empfohlen: deaktiviert Schlagschatten und teure Vollreflexionen, behält Atmosphäre und Himmelsreflexionen.",
  profileEfficient: "Effizient",
  profileEfficientBody: "Maximale Flüssigkeit und Akkulaufzeit: deaktiviert Schatten, Atmosphäre, Antialiasing und Wasserreflexionen.",
  profileQuality: "Mod-Standard",
  profileQualityBody: "Entfernt die von der Suite verwalteten visuellen Optionen, sodass echte Mod-Standards zurückkehren. Beste Qualität, Dramatic Shape kann auf Smartphones jedoch ruckeln.",
  measuredPerformance: "Zuletzt gemessene Sitzung",
  noMeasurement: "Spiele mindestens zehn Sekunden, um lokale Frame-Metriken zu erfassen.",
  saveSync: "Intervall der Save-Spiegelung",
  automaticChecks: "Automatische Update-Prüfung",
  automaticChecksBody: "Nur nach Zustimmung; es wird niemals automatisch installiert.",
  updateFrequency: "Prüfintervall",
  updateCenter: "Update-Zentrale",
  updateCenterBody: "Gen1Recomp, LÖVE-Web-Runtime und alle aktualisierbaren Mods an einem Ort.",
  downloadManager: "Download-Manager",
  downloadManagerBody: "Automatische Wiederholungen, sichere HTTP-Fortsetzung und Integritätsprüfung.",
  noDownloads: "Keine Downloads",
  noDownloadsBody: "Komponenten-, IPA- und GitHub-Mod-Downloads erscheinen hier.",
  downloadPartialNotice: "Teildaten bleiben nach einer Unterbrechung lokal erhalten. Wenn ein Server Range ignoriert, startet die Datei sauber neu; Teildaten werden nie installiert.",
  downloadQueued: "Warteschlange",
  downloadInProgress: "Wird geladen",
  downloadRetry: "Neuer Versuch",
  downloadVerifying: "Integrität wird geprüft",
  downloadPaused: "Pausiert · fortsetzbar",
  downloadCompleted: "Verifiziert · bereit",
  downloadFailed: "Fehlgeschlagen · fortsetzbar",
  pause: "Pausieren",
  resume: "Fortsetzen",
  clearDownload: "Entfernen",
  httpResume: "HTTP-Fortsetzung",
  cleanRestart: "sauberer Neustart",
  cancelDownloadTitle: "Download abbrechen?",
  cancelDownloadBody: "Gespeicherte Teildaten werden sicher entfernt.",
  cancelDownloadAction: "Download abbrechen",
  resumingDownload: "wird fortgesetzt",
  resumedDownloadReady: "verifiziert; Aktion erneut öffnen, um zu installieren",
  checkEverything: "Alle Komponenten prüfen",
  updateAllMods: "Alle verfügbaren Mod-Updates installieren",
  engineComponent: "Gen1Recomp-Engine",
  runtimeComponent: "LÖVE-Web-Runtime",
  bundled: "Gebündelt",
  installedComponent: "Installierte Überschreibung",
  current: "Aktuell",
  updateAvailableLabel: "Update verfügbar",
  sourceChanged: "Neuer Upstream-Quellstand vorhanden; nur ein kompatibles Runtime-Bundle installieren.",
  installEngineUpdate: "Engine-Update installieren",
  executionLayerComponent: "Ausführungsschicht",
  importExecutionLayer: "Update der Ausführungsschicht importieren",
  resetExecutionLayer: "Erzeugte Ausführungsschicht wiederherstellen",
  executionLayerNotice: "Ausführungsschichten enthalten ausführbares Lua und laufen vor dem unveränderten Core. Importiere nur eine vertrauenswürdige Schicht. Die Suite verlangt eine neuere Schichtversion, exakte Core-Kompatibilität, Revision 9, deterministische Dateihashes und transaktionale Aktivierung.",
  importRuntimeBundle: "Runtime-Bundle importieren",
  resetEngine: "Gebündelte Engine wiederherstellen",
  resetRuntime: "Gebündelte Web-Runtime wiederherstellen",
  runtimeBundleNotice: "Runtime-Bundles enthalten ausführbares JavaScript und WebAssembly. Importiere nur vertrauenswürdige Compatibility-/No-Pthreads-Bundles; deklarierte Hashes und WebAssembly-Header werden geprüft.",
  checkingEverything: "Engine, Runtime und Mods werden geprüft…",
  checkedEverything: "Update-Prüfung abgeschlossen",
  noUpdates: "Alles Aktualisierbare ist aktuell.",
  updatesFound: "Updates verfügbar",
  openRuntimeSource: "Runtime-Quelle öffnen",
  profileAppliedNextLaunch: "Das Profil gilt beim nächsten Start und wird in den eigenen Mod-Optionen angezeigt.",
  externalModNotice: "Dies ist ein externes Community-Projekt und wird von der Suite weder gebündelt noch weiterverteilt. Das Repository beschreibt sich als originalgetreue Kopie von Dramatic Shape 1.8.2 und schränkt die Weiterverteilung späteren Codes ein. Das ZIP wird erst nach Bestätigung direkt aus dem GitHub-Release geladen.",
}

export const T = isGerman ? DE : EN
