import assert from "node:assert/strict"
import { readFileSync, writeFileSync } from "node:fs"
import { patchOfficialEngineLove } from "../modules/engine-patcher.ts"
import { decodeUtf8, extractLocalZipEntry, readLocalZip } from "../modules/zip.ts"

const sourcePath = process.argv[2]
if (sourcePath == null) throw new Error("Usage: test_engine_update.mjs /path/to/official.love [output.love]")
const source = new Uint8Array(readFileSync(sourcePath))
const bit = new Uint8Array(readFileSync(new URL("../runtime/patches/bit.lua", import.meta.url)))
const patched = patchOfficialEngineLove(source, bit)
const entries = readLocalZip(patched)
const files = new Map()
for (const entry of entries) {
  if (entry.type === "file") files.set(entry.path, extractLocalZipEntry(patched, entry))
}
assert.equal(files.has("bit.lua"), true)
assert.equal(files.has("main.lua"), true)
assert.equal(files.has("src/mods/Loader.lua"), true)
assert.equal(files.has("src/debug/SwitchDiagnostics.lua"), true)
const main = decodeUtf8(files.get("main.lua"))
const loader = decodeUtf8(files.get("src/mods/Loader.lua"))
const switchDiagnostics = decodeUtf8(files.get("src/debug/SwitchDiagnostics.lua"))
const saveData = decodeUtf8(files.get("src/core/SaveData.lua"))
assert.match(main, /web-rom-/)
assert.match(main, /getCanvasFormats\(true\)/)
assert.match(main, /rewriteWebImageEncodeGuard/)
assert.match(main, /@mods\/overworld_wild_spawns\/lib\/spawn_render\.lua/)
assert.match(main, /imageFormat ~= "rgba8" and imageFormat ~= "rgba16"/)
assert.match(main, /nativeLoadstring = loadstring/)
assert.match(main, /rewritePotatoVoxel144WebGuards/)
assert.match(main, /@mods\/potato_voxel\/lib\/SpriteBillboards\.lua/)
assert.match(main, /@mods\/potato_voxel\/lib\/OverworldBattle\.lua/)
assert.match(main, /@mods\/potato_voxel\/lib\/VoxelScene\.lua/)
assert.match(main, /\[native-lua-error\]/)
assert.match(main, /debug\.traceback\("Unhandled Lua error: "/)
assert.match(switchDiagnostics, /filesystem\.getInfo\(ERROR_LOG, "file"\)/)
assert.doesNotMatch(switchDiagnostics, /local existing = filesystem\.read\(ERROR_LOG\)/)
assert.match(loader, /NATIVE_MOD_STATE_FILE/)
assert.match(loader, /NATIVE_MOD_OPTIONS_FILE/)
assert.match(loader, /_finalizeNativeOptions/)
assert.match(loader, /nativeSchemaRows/)
assert.match(loader, /state\.managed/)
assert.match(loader, /applyBuckets\(state\.profile\)/)
assert.match(loader, /applyBuckets\(state\.values\)/)
assert.match(saveData, /GEN1RECOMP_NATIVE_OPTIONS_CAPTURE/)
assert.match(loader, /optional mod assets must probe/)
assert.equal(entries.filter(entry => entry.type === "file").length, readLocalZip(source).filter(entry => entry.type === "file").length + 1)
if (process.argv[3] != null) writeFileSync(process.argv[3], patched)
console.log("Dynamic engine patch test passed:", patched.length, "bytes,", files.size, "files")
